{% set name = "bmi-cxx" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a14ad573bf57203c125552b6ff3deeab6cbe6c9e4935d090d65e175ed4dbfbdd

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/bmi.hxx          # [unix]
    - test -f $PREFIX/lib/pkgconfig/bmicxx.pc  # [unix]
    - if not exist %LIBRARY_INC%\\bmi.hxx exit 1               # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\bmicxx.pc exit 1  # [win]

about:
  home: https://bmi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'C++ specification for the Basic Model Interface'
  description: |
    C++ bindings for the CSDMS Basic Model Interface (BMI). This package
    includes a header file with an interface to be implemented by a
    model developer when they add a BMI to their model.
  doc_url: https://bmi.readthedocs.io
  dev_url: https://github.com/csdms/bmi-cxx

extra:
  recipe-maintainers:
    - mdpiper
    - mcflugen
